modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Uraneptus/SnowPig-forge/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snow-pig" #optional
logoFile="snowpig-banner.png"
logoBlur=false
credits="Sounds by Luz#8017"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="optional"
    versionRange="[1.2,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.snowpig]
    catalogueImageIcon= "snowpig-icon.png"
